name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # We use this for a single test that runs Bun for a subprocess
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: enable corepack
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
      - name: cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashfiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install --immutable

      - run: yarn build

      - run: yarn lint

      - run: yarn prettier

      - name: Run tests
        run: yarn test
        env:
          REFORGE_INTEGRATION_TEST_SDK_KEY: ${{ secrets.REFORGE_INTEGRATION_TEST_SDK_KEY }}
          REFORGE_TEST_API_KEY: ${{ secrets.REFORGE_TEST_API_KEY }}

      - name: Validate cjs version
        run: node dist/reforge.cjs

      - name: Validate esm version
        run: node dist/reforge.mjs
