name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # We use this for a single test that runs Bun for a subprocess
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: npm ci
      - run: npm run build --if-present

      - run: npm run lint

      - run: npm run format

      - name: Run tests
        run: npm test
        env:
          REFORGE_INTEGRATION_TEST_SDK_KEY: ${{ secrets.REFORGE_INTEGRATION_TEST_SDK_KEY }}
          REFORGE_TEST_API_KEY: ${{ secrets.REFORGE_TEST_API_KEY }}

      - name: Validate cjs version
        run: node dist/reforge.cjs

      - name: Validate esm version
        run: node dist/reforge.mjs
